spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/myproject
    username: myuser
    password: ${DB_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

portal:
  frontend:
    url: "http://localhost:3000"

telegram:
  bot:
    name: "PhystechPortalBot"
    token: "token"
